name: Portfolio Deployment Workflow

on:
    push:
        branches:
            - main
    workflow_dispatch:
permissions:
    pages: write # to deploy to GitHub Pages
    id-token: write # to authenticate with GitHub Pages
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deploy-pages.outputs.page_url }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setupv Github Pages

              uses: actions/configure-pages@v4
            - #static code artifacts 
              name: Upload static files
              uses: actions/upload-pages-artifact@v4
              with: 
                path: .

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4 